//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedRegistration.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fund
    {
        public Fund()
        {
            this.PatientFundInfoes = new HashSet<PatientFundInfo>();
            this.PaymentInfoes = new HashSet<PaymentInfo>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<PatientFundInfo> PatientFundInfoes { get; set; }
        public virtual ICollection<PaymentInfo> PaymentInfoes { get; set; }
    }
}
